services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: gestao_vagas_postgres
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=gestao_vagas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  postgres_data:
